# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/example

baseURL = 'https://example.com/public-docs'
title = 'Hugo DocBook'
theme = 'hugo-book'
disableKinds = ['taxonomy', 'taxonomyTerm']
# themesDir = '../..'

# Book configuration
disablePathToLower = true

# Code highlight
pygmentsStyle = 'monokailight'
pygmentsCodeFences = true

enableEmoji = true